services:
  biz.users.create:
    class: HateoasInc\Bundle\ExampleBundle\Service\UserBuilder
  biz.users.update:
    class: HateoasInc\Bundle\ExampleBundle\Service\UserMutator

  security.access.user_group_voter:
    class: HateoasInc\Bundle\ExampleBundle\Security\Authorization\Voter\UserGroupVoter
    public: false
    tags:
      - { name: security.voter }
  security.access.user_voter:
    class: HateoasInc\Bundle\ExampleBundle\Security\Authorization\Voter\UserVoter
    public: false
    tags:
      - { name: security.voter }
  security.access.article_voter:
    class: HateoasInc\Bundle\ExampleBundle\Security\Authorization\Voter\ArticleVoter
    public: false
    tags:
      - { name: security.voter }
  security.access.post_voter:
    class: HateoasInc\Bundle\ExampleBundle\Security\Authorization\Voter\PostVoter
    public: false
    tags:
      - { name: security.voter }
  security.access.comment_voter:
    class: HateoasInc\Bundle\ExampleBundle\Security\Authorization\Voter\CommentVoter
    public: false
    tags:
      - { name: security.voter }
